/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Database;
import backend.Security;
import backend.Session;
import component.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import stringProcessing.*;

/**
 *
 * @author ASUS
 */
public class DosenForm extends javax.swing.JFrame {

    private Dimension screenSize;
    private Database db;
    private Session session;
    private Security security;
    private InputMatkulMahasiswa stringProcessor;
    
    private BufferedImage bImage;
    private ImageIcon icon;
    private ImageIcon iconEdit;
    private ImageIcon iconAdd;
    private ImageIcon iconSave;
    private ImageIcon imageStep4;
    
    /**
     * Creates new form WelcomeForm
     */
    public DosenForm(Database db, Session session) {
        initComponents();
        this.icon = new ImageIcon(MainForm.class.getResource("/res/LOGO-StudyAdvisor.png"));
        this.setIconImage(this.icon.getImage());
        
        this.setMinimumSize(Styling.WXGA_SCREEN);
        this.setSize(Styling.WXGA_SCREEN);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); //SetFullscreen
        
        this.db = db;
        this.session = session;        
        this.stringProcessor = new InputMatkulMahasiswa();
        
        this.jLabel2.setText("Selamat Datang, " + this.session.getDosen().getNama() + "!");
        this.panelEditMataKuliah.setVisible(false);
        
    }
    
    private void showInstructions() {
        this.getContentPane().remove(this.panelWelcome);
        this.panelWelcome = new PanelInstruksi();
        this.panelWelcome.setVisible(true);
        JPanel newContentPane = new JPanel();
        newContentPane.setSize(this.getWidth(), this.getHeight());
        newContentPane.setMinimumSize(new Dimension(1024, 1024));
        newContentPane.setMaximumSize(this.getMaximumSize());
        newContentPane.add(this.panelWelcome);
        this.getContentPane().add(newContentPane);
        this.invalidate();
        this.revalidate();
        this.repaint();
        //if(this.screenSize != null) this.screenSize.setSize(this.getWidth(), this.getHeight());
        Styling.refreshSize(this);
        Styling.centeringPanel(this, this.panelWelcome);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWelcome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnEditMataKuliah = new javax.swing.JPanel();
        this.bImage = null;
        try {
            bImage = ImageIO.read(new File(DosenForm.class.getResource("/res/ICON-Edit.png").getFile()));
            Image image = bImage.getScaledInstance(32, 32, Image.SCALE_SMOOTH);
            this.iconEdit = new ImageIcon(image);
        } catch (Exception ex){
            System.out.println(ex.toString());
        }
        iconEditMataKuliah = new javax.swing.JLabel(this.iconEdit);
        lblEditMataKuliah = new javax.swing.JLabel();
        panelEditMataKuliah = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textInput = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelAmbilMatkul = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField1 = new CustomTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField2 = new CustomTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField3 = new CustomTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField4 = new CustomTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField5 = new CustomTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField6 = new CustomTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnEditMataKuliah1 = new javax.swing.JPanel();
        this.bImage = null;
        try {
            bImage = ImageIO.read(new File(DosenForm.class.getResource("/res/ICON-Save.png").getFile()));
            Image image = bImage.getScaledInstance(32, 32, Image.SCALE_SMOOTH);
            this.iconSave = new ImageIcon(image);
        } catch (Exception ex){
            System.out.println(ex.toString());
        }
        iconEditMataKuliah1 = new javax.swing.JLabel(this.iconSave);
        lblEditMataKuliah1 = new javax.swing.JLabel();
        btnEditMataKuliah2 = new CustomSecondaryButton();
        this.bImage = null;
        try {
            bImage = ImageIO.read(new File(DosenForm.class.getResource("/res/ICON-AddPlus.png").getFile()));
            Image image = bImage.getScaledInstance(32, 32, Image.SCALE_SMOOTH);
            this.iconAdd = new ImageIcon(image);
        } catch (Exception ex){
            System.out.println(ex.toString());
        }
        iconEditMataKuliah2 = new javax.swing.JLabel(this.iconAdd);
        lblEditMataKuliah2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Oswald", 0, 10)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1024, 1024));
        setSize(new java.awt.Dimension(1024, 768));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        panelWelcome.setBackground(new java.awt.Color(255, 255, 255));
        panelWelcome.setPreferredSize(new java.awt.Dimension(1024, 720));
        panelWelcome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Selamat Datang, namaAnu!");
        panelWelcome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Oswald", 0, 36)); // NOI18N
        jLabel5.setText("4");
        panelWelcome.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1173, 512, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SAYA MENGERTI, LANJUTKAN >");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelWelcome.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 610, 313, 57));

        jPanel1.setBackground(new java.awt.Color(243, 156, 18));

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Dosen");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("999");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addContainerGap())
        );

        panelWelcome.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 180, 180));

        jPanel2.setBackground(new java.awt.Color(221, 75, 57));

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Mata Kuliah");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("999");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        panelWelcome.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 180, 180));

        jPanel3.setBackground(new java.awt.Color(0, 192, 239));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Mahasiswa");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("999");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        panelWelcome.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 180, 180));

        jPanel4.setBackground(new java.awt.Color(0, 166, 90));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Bidang");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("999");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        panelWelcome.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 180, 180));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        panelWelcome.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel23.setText("What's up?");
        panelWelcome.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 200, -1));

        btnEditMataKuliah.setBackground(new java.awt.Color(236, 240, 241));
        btnEditMataKuliah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMataKuliahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMataKuliahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMataKuliahMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditMataKuliahMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditMataKuliahMouseReleased(evt);
            }
        });

        iconEditMataKuliah.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        iconEditMataKuliah.setForeground(new java.awt.Color(51, 51, 51));
        iconEditMataKuliah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblEditMataKuliah.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblEditMataKuliah.setForeground(new java.awt.Color(51, 51, 51));
        lblEditMataKuliah.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEditMataKuliah.setText("Edit Mata Kuliah");

        javax.swing.GroupLayout btnEditMataKuliahLayout = new javax.swing.GroupLayout(btnEditMataKuliah);
        btnEditMataKuliah.setLayout(btnEditMataKuliahLayout);
        btnEditMataKuliahLayout.setHorizontalGroup(
            btnEditMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditMataKuliahLayout.createSequentialGroup()
                .addComponent(iconEditMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblEditMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        btnEditMataKuliahLayout.setVerticalGroup(
            btnEditMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditMataKuliahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(iconEditMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblEditMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelWelcome.add(btnEditMataKuliah, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 260, 60));

        panelEditMataKuliah.setBackground(new java.awt.Color(255, 255, 255));
        panelEditMataKuliah.setPreferredSize(new java.awt.Dimension(1024, 720));
        panelEditMataKuliah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Klik pada baris tabel untuk mengedit");
        panelEditMataKuliah.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 107, -1, -1));

        textInput.setColumns(20);
        textInput.setRows(5);
        textInput.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                textInputInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(textInput);

        panelEditMataKuliah.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 410, 80));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("KONVERSI KE TABEL");
        jButton2.setBorder(null);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelEditMataKuliah.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 80, 57));

        tabelAmbilMatkul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Smt.", "Mata Kuliah", "SKS", "Logic", "Math", "Memo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelAmbilMatkul);
        if (tabelAmbilMatkul.getColumnModel().getColumnCount() > 0) {
            tabelAmbilMatkul.getColumnModel().getColumn(0).setResizable(false);
            tabelAmbilMatkul.getColumnModel().getColumn(0).setPreferredWidth(1);
            tabelAmbilMatkul.getColumnModel().getColumn(1).setResizable(false);
            tabelAmbilMatkul.getColumnModel().getColumn(1).setPreferredWidth(1);
            tabelAmbilMatkul.getColumnModel().getColumn(2).setResizable(false);
            tabelAmbilMatkul.getColumnModel().getColumn(2).setPreferredWidth(128);
            tabelAmbilMatkul.getColumnModel().getColumn(3).setResizable(false);
            tabelAmbilMatkul.getColumnModel().getColumn(3).setPreferredWidth(1);
            tabelAmbilMatkul.getColumnModel().getColumn(4).setResizable(false);
            tabelAmbilMatkul.getColumnModel().getColumn(4).setPreferredWidth(1);
            tabelAmbilMatkul.getColumnModel().getColumn(5).setResizable(false);
            tabelAmbilMatkul.getColumnModel().getColumn(5).setPreferredWidth(1);
            tabelAmbilMatkul.getColumnModel().getColumn(6).setResizable(false);
            tabelAmbilMatkul.getColumnModel().getColumn(6).setPreferredWidth(1);
        }

        panelEditMataKuliah.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 540, 410));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Oswald", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setText("< KEMBALI");
        jButton4.setBorder(null);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton4MouseReleased(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelEditMataKuliah.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 210, 57));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel18.setText("Edit Mata Kuliah");
        panelEditMataKuliah.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 50, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel24.setText("Semester");
        panelEditMataKuliah.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 190, 20));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        panelEditMataKuliah.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 280, 50));
        jTextField1.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.DARK_GRAY));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel25.setText("Nama Mata Kuliah");
        panelEditMataKuliah.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 270, 20));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        panelEditMataKuliah.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 280, 50));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel26.setText("SKS");
        panelEditMataKuliah.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 270, 20));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        panelEditMataKuliah.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 280, 50));
        jTextField1.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.DARK_GRAY));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel27.setText("Logic");
        panelEditMataKuliah.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 70, 30));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        panelEditMataKuliah.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 70, 50));
        jTextField1.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.DARK_GRAY));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel28.setText("Math");
        panelEditMataKuliah.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 70, 30));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        panelEditMataKuliah.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 70, 50));
        jTextField1.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.DARK_GRAY));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel29.setText("Memo");
        panelEditMataKuliah.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 90, 30));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        panelEditMataKuliah.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 470, 70, 50));
        jTextField1.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.DARK_GRAY));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox1.setText("  Mata Kuliah Wajib");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        panelEditMataKuliah.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, -1, -1));

        btnEditMataKuliah1.setBackground(new java.awt.Color(51, 153, 255));
        btnEditMataKuliah1.setForeground(new java.awt.Color(255, 255, 255));
        btnEditMataKuliah1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMataKuliah1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMataKuliah1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMataKuliah1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditMataKuliah1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditMataKuliah1MouseReleased(evt);
            }
        });

        iconEditMataKuliah1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        iconEditMataKuliah1.setForeground(new java.awt.Color(51, 51, 51));
        iconEditMataKuliah1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblEditMataKuliah1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblEditMataKuliah1.setForeground(new java.awt.Color(255, 255, 255));
        lblEditMataKuliah1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEditMataKuliah1.setText("Simpan");

        javax.swing.GroupLayout btnEditMataKuliah1Layout = new javax.swing.GroupLayout(btnEditMataKuliah1);
        btnEditMataKuliah1.setLayout(btnEditMataKuliah1Layout);
        btnEditMataKuliah1Layout.setHorizontalGroup(
            btnEditMataKuliah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditMataKuliah1Layout.createSequentialGroup()
                .addComponent(iconEditMataKuliah1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblEditMataKuliah1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnEditMataKuliah1Layout.setVerticalGroup(
            btnEditMataKuliah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditMataKuliah1Layout.createSequentialGroup()
                .addGroup(btnEditMataKuliah1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconEditMataKuliah1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(lblEditMataKuliah1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelEditMataKuliah.add(btnEditMataKuliah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 600, 180, 60));

        btnEditMataKuliah2.setBackground(new java.awt.Color(236, 240, 241));
        btnEditMataKuliah2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMataKuliah2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMataKuliah2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMataKuliah2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditMataKuliah2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditMataKuliah2MouseReleased(evt);
            }
        });

        iconEditMataKuliah2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        iconEditMataKuliah2.setForeground(new java.awt.Color(51, 51, 51));
        iconEditMataKuliah2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblEditMataKuliah2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lblEditMataKuliah2.setForeground(new java.awt.Color(51, 51, 51));
        lblEditMataKuliah2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEditMataKuliah2.setText("Tambah");

        javax.swing.GroupLayout btnEditMataKuliah2Layout = new javax.swing.GroupLayout(btnEditMataKuliah2);
        btnEditMataKuliah2.setLayout(btnEditMataKuliah2Layout);
        btnEditMataKuliah2Layout.setHorizontalGroup(
            btnEditMataKuliah2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditMataKuliah2Layout.createSequentialGroup()
                .addComponent(iconEditMataKuliah2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblEditMataKuliah2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnEditMataKuliah2Layout.setVerticalGroup(
            btnEditMataKuliah2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEditMataKuliah2Layout.createSequentialGroup()
                .addGroup(btnEditMataKuliah2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconEditMataKuliah2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(lblEditMataKuliah2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelEditMataKuliah.add(btnEditMataKuliah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 180, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(panelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEditMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelEditMataKuliah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        if(this.panelWelcome.isVisible()) Styling.centeringPanel(this, this.panelWelcome);
        if(this.panelEditMataKuliah.isVisible()) Styling.centeringPanel(this, panelEditMataKuliah);
    }//GEN-LAST:event_formComponentResized

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Styling.centeringPanel(this, this.panelWelcome);
        Styling.refreshSize(this);
        
        System.out.println(this.panelWelcome.getSize());
    }//GEN-LAST:event_formWindowActivated

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(this.tabelAmbilMatkul.getRowCount() != 0){
            int jumlahRow = ((DefaultTableModel)(this.tabelAmbilMatkul.getModel())).getRowCount();
            for(int i=0; i<jumlahRow; i++){
                ((DefaultTableModel)(this.tabelAmbilMatkul.getModel())).removeRow(0);
            }
        }
        int nomorSekarang = 1;
        int semesterSekarang = 1;
        InputMatkulMahasiswaJSON json;
        
        for(String line: textInput.getText().split("\\n")){
            if(!line.equals("")){
                json = this.stringProcessor.extract(line);
                if(json.isAccepted()){
                    ((DefaultTableModel)(this.tabelAmbilMatkul.getModel())).addRow(new Object[]{nomorSekarang, semesterSekarang, json.getIdMatkul(), json.getNilai()});
                    nomorSekarang++;
                }
            }else{
                semesterSekarang++;
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.panelEditMataKuliah.setVisible(true);
        this.panelWelcome.setVisible(false);

        Styling.refreshSize(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased

    }//GEN-LAST:event_jButton1MouseReleased

    private void textInputInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_textInputInputMethodTextChanged
        
    }//GEN-LAST:event_textInputInputMethodTextChanged

    private void jButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.panelEditMataKuliah.setVisible(false);
        this.panelWelcome.setVisible(true);

        Styling.refreshSize(this);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnEditMataKuliahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMataKuliahMouseEntered
        this.btnEditMataKuliah.setBackground(Color.decode("#bdc3c7"));
    }//GEN-LAST:event_btnEditMataKuliahMouseEntered

    private void btnEditMataKuliahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMataKuliahMouseExited
        this.btnEditMataKuliah.setBackground(Color.decode("#ecf0f1"));
    }//GEN-LAST:event_btnEditMataKuliahMouseExited

    private void btnEditMataKuliahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMataKuliahMousePressed
        this.btnEditMataKuliah.setBackground(Color.decode("#adb3b7"));
    }//GEN-LAST:event_btnEditMataKuliahMousePressed

    private void btnEditMataKuliahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMataKuliahMouseReleased
        this.btnEditMataKuliah.setBackground(Color.decode("#bdc3c7"));
    }//GEN-LAST:event_btnEditMataKuliahMouseReleased

    private void btnEditMataKuliahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMataKuliahMouseClicked
        
    }//GEN-LAST:event_btnEditMataKuliahMouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed

    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnEditMataKuliah1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMataKuliah1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMataKuliah1MouseClicked

    private void btnEditMataKuliah1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMataKuliah1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMataKuliah1MouseEntered

    private void btnEditMataKuliah1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMataKuliah1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMataKuliah1MouseExited

    private void btnEditMataKuliah1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMataKuliah1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMataKuliah1MousePressed

    private void btnEditMataKuliah1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMataKuliah1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMataKuliah1MouseReleased

    private void btnEditMataKuliah2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMataKuliah2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMataKuliah2MouseClicked

    private void btnEditMataKuliah2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMataKuliah2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMataKuliah2MouseEntered

    private void btnEditMataKuliah2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMataKuliah2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMataKuliah2MouseExited

    private void btnEditMataKuliah2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMataKuliah2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMataKuliah2MousePressed

    private void btnEditMataKuliah2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMataKuliah2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditMataKuliah2MouseReleased

    /**
     * @param args the command line arguments
     */
    
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
    //    java.awt.EventQueue.invokeLater(new Runnable() {
    //        public void run(Database db, Session session) {
    //            new WelcomeForm(db, session).setVisible(true);
    //        }
    //    });
    //}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnEditMataKuliah;
    private javax.swing.JPanel btnEditMataKuliah1;
    private javax.swing.JPanel btnEditMataKuliah2;
    private javax.swing.JLabel iconEditMataKuliah;
    private javax.swing.JLabel iconEditMataKuliah1;
    private javax.swing.JLabel iconEditMataKuliah2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblEditMataKuliah;
    private javax.swing.JLabel lblEditMataKuliah1;
    private javax.swing.JLabel lblEditMataKuliah2;
    private javax.swing.JPanel panelEditMataKuliah;
    private javax.swing.JPanel panelWelcome;
    private javax.swing.JTable tabelAmbilMatkul;
    private javax.swing.JTextArea textInput;
    // End of variables declaration//GEN-END:variables
}
